/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.69
 * Generated at: 2021-10-19 12:29:16 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import org.omg.CORBA.INTERNAL;
import java.io.PrintWriter;
import bbs.Bbs;
import bbs.BbsDAO;

public final class view_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("org.omg.CORBA.INTERNAL");
    _jspx_imports_classes.add("java.io.PrintWriter");
    _jspx_imports_classes.add("bbs.Bbs");
    _jspx_imports_classes.add("bbs.BbsDAO");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>스트릿 우먼 파이터</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"./css/js.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"./css/bootstrap.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"./css/custom.css\">\r\n");
      out.write("<link rel=\"icon\" href=\"./p1/favicon1.ico\">\r\n");
      out.write("<!-- jQuery CDN과 bootstrap.js 파일의 스크립트를 사용해서 내비게이션 바가 동작한다. -->\r\n");
      out.write("<script type=\"text/javascript\" src=\"https://code.jquery.com/jquery-3.6.0.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"./js/bootstrap.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	");
 
		String userID = null;
		if(session.getAttribute("userID") != null) {
			userID = (String) session.getAttribute("userID");
		}
		int bbsID = 0;
		if (request.getParameter("bbsID") != null) {
			bbsID = Integer.parseInt(request.getParameter("bbsID"));
		}
		if (bbsID == 0) {
			PrintWriter script = response.getWriter();
			script.println("<script>");
			script.println("alert('유효하지 않는 글입니다.')");
			script.println("location.href = 'boardPage.jsp'");
			script.println("</script>");
		}
		Bbs bbs = new BbsDAO().getBbs(bbsID);
		
	
      out.write("\r\n");
      out.write("\r\n");
      out.write("<nav class=\"navbar navbar-default\">\r\n");
      out.write("	<div class=\"container-fluid\">\r\n");
      out.write("		<div class=\"navbar-header\">\r\n");
      out.write("			<button type=\"button\" class=\"navbar-toggle collapsed\" data-toggle=\"collapse\" data-target=\"#bs-example-navbar-collapse-1\" \r\n");
      out.write("				aria-expanded=\"false\">\r\n");
      out.write("				<span class=\"sr-only\"></span>\r\n");
      out.write("				<span class=\"icon-bar\"></span>\r\n");
      out.write("				<span class=\"icon-bar\"></span>\r\n");
      out.write("				<span class=\"icon-bar\"></span>\r\n");
      out.write("			</button>\r\n");
      out.write("			<a class=\"navbar-brand\" href=\"mainhome.jsp\">스트릿 우먼 파이터</a>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"collapse navbar-collapse\" id=\"bs-example-navbar-collapse-1\">\r\n");
      out.write("			<ul class=\"nav navbar-nav\">\r\n");
      out.write("				\r\n");
      out.write("				<li class=\"dropdown\">\r\n");
      out.write("					<a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\" role=\"button\" aria-haspopup=\"true\" aria-expanded=\"false\">\r\n");
      out.write("						프로그램 소개<span class=\"caret\"></span>\r\n");
      out.write("					</a>\r\n");
      out.write("					<ul class=\"dropdown-menu\">\r\n");
      out.write("						<li><a href=\"mainhome.jsp\">프로그램 소개</a></li>\r\n");
      out.write("					</ul>\r\n");
      out.write("				</li>\r\n");
      out.write("				\r\n");
      out.write("				<li class=\"dropdown\">\r\n");
      out.write("					<a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\" role=\"button\" aria-haspopup=\"true\" aria-expanded=\"false\">\r\n");
      out.write("						크루 소개<span class=\"caret\"></span>\r\n");
      out.write("					</a>\r\n");
      out.write("					<ul class=\"dropdown-menu\">\r\n");
      out.write("						<li><a href=\"crewView.jsp?crew=cocan\">CocaNButter</a></li>\r\n");
      out.write("						<li><a href=\"crewView.jsp?crew=ygx\">YGX</a></li>\r\n");
      out.write("						<li><a href=\"crewView.jsp?crew=lachica\">LACHICA</a></li>\r\n");
      out.write("						<li><a href=\"crewView.jsp?crew=want\">WANT</a></li>\r\n");
      out.write("						<li><a href=\"crewView.jsp?crew=wayb\">WAYB</a></li>\r\n");
      out.write("						<li><a href=\"crewView.jsp?crew=hook\">HOOK</a></li>\r\n");
      out.write("						<li><a href=\"crewView.jsp?crew=holybang\">HolyBang</a></li>\r\n");
      out.write("						<li><a href=\"crewView.jsp?crew=prowdmon\">PROWDMON</a></li>\r\n");
      out.write("					</ul>\r\n");
      out.write("				</li>\r\n");
      out.write("				\r\n");
      out.write("				<li class=\"dropdown\">\r\n");
      out.write("					<a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\" role=\"button\" aria-haspopup=\"true\" aria-expanded=\"false\">\r\n");
      out.write("						게시판<span class=\"caret\"></span>\r\n");
      out.write("					</a>\r\n");
      out.write("					<ul class=\"dropdown-menu\">\r\n");
      out.write("						<li><a href=\"boardPage.jsp\">게시판</a></li>\r\n");
      out.write("					</ul>\r\n");
      out.write("				</li>\r\n");
      out.write("\r\n");
      out.write("			</ul>\r\n");
      out.write(" 			<form class=\"navbar-form navbar-right\">\r\n");
      out.write("				<div class=\"form-group\">\r\n");
      out.write("					<input type=\"text\" class=\"form-control\" placeholder=\"검색 내용을 입력하세요.\"/>\r\n");
      out.write("				<button type=\"button\" class=\"btn btn-default\">검색</button>\r\n");
      out.write("				</div>\r\n");
      out.write("			</form>\r\n");
      out.write("			");

			 // 접속하기는 로그인이 되어있지 않은 경우만 나오게한다
				if(userID == null) {
			
      out.write("\r\n");
      out.write("		\r\n");
      out.write("			<div class=\"nav navbar-nav navbar-right\">\r\n");
      out.write("				<li class=\"dropdown\">\r\n");
      out.write("					<a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\" role=\"button\" aria-haspopup=\"true\" aria-expanded=\"false\">\r\n");
      out.write("						접속하기<span class=\"caret\"></span>\r\n");
      out.write("					</a>\r\n");
      out.write("					<ul class=\"dropdown-menu\">\r\n");
      out.write("						<li><a href=\"mainlogin.jsp\">로그인</a></li>\r\n");
      out.write("						<li><a href=\"register.jsp\">회원가입</a></li>\r\n");
      out.write("					</ul>\r\n");
      out.write("					\r\n");
      out.write("				</li>\r\n");
      out.write("			</div>\r\n");
      out.write("			");

			 // 로그인이 되어있는 사람만 볼수 있는 화면
				} else {
			
      out.write("\r\n");
      out.write("			<div class=\"nav navbar-nav navbar-right\">\r\n");
      out.write("				<li class=\"dropdown\">\r\n");
      out.write("					<a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\" role=\"button\" aria-haspopup=\"true\" aria-expanded=\"false\">\r\n");
      out.write("						회원관리<span class=\"caret\"></span>\r\n");
      out.write("					</a>\r\n");
      out.write("					<ul class=\"dropdown-menu\">\r\n");
      out.write("						<li><a href=\"logoutAction.jsp\">로그아웃</a></li>\r\n");
      out.write("					</ul>\r\n");
      out.write("					\r\n");
      out.write("				</li>\r\n");
      out.write("			</div>\r\n");
      out.write("			");

				}
			
      out.write("\r\n");
      out.write("			\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</nav>\r\n");
      out.write("<br><br>\r\n");
      out.write("	<div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("		<div class=\"row\">\r\n");
      out.write("			<table class=\"table table-striped\"\r\n");
      out.write("				style=\"text-align: center; border: 1px slild #dddddd\">\r\n");
      out.write("				<thead>\r\n");
      out.write("					<tr>\r\n");
      out.write("						<th colspan=\"3\"\r\n");
      out.write("							style=\"background-color: #eeeeee; color: black; text-align: center;\">게시판\r\n");
      out.write("							글보기 </th>\r\n");
      out.write("					</tr>\r\n");
      out.write("				</thead>\r\n");
      out.write("				<tbody>\r\n");
      out.write("					<tr>\r\n");
      out.write("						<td style=\"width:20%;\">글제목</td>\r\n");
      out.write("						<td colspan=\"2\">");
      out.print( bbs.getBbsTitle().replaceAll(" ", "&nbsp;").replaceAll("<", "&lt;").replaceAll(">", "&gt;").replaceAll("\n", "<br>") );
      out.write("</td>\r\n");
      out.write("					</tr>\r\n");
      out.write("					<tr>\r\n");
      out.write("						<td>작성자</td>\r\n");
      out.write("						<td colspan=\"2\">");
      out.print( bbs.getUserID() );
      out.write("</td>\r\n");
      out.write("					</tr>\r\n");
      out.write("					<tr>\r\n");
      out.write("						<td>작성일자</td>\r\n");
      out.write("						<td colspan=\"2\">");
      out.print( bbs.getBbsDate() );
      out.write("</td>\r\n");
      out.write("					</tr>\r\n");
      out.write("					<tr>\r\n");
      out.write("						<td>내용</td>\r\n");
      out.write("						<td colspan=\"2\"  style=\"min-height:200px; text-align:left;\">");
      out.print( bbs.getBbsContent().replaceAll(" ", "&nbsp;").replaceAll("<", "&lt;").replaceAll(">", "&gt;").replaceAll("\n", "<br>") );
      out.write("</td>\r\n");
      out.write("					</tr>\r\n");
      out.write("				</tbody>\r\n");
      out.write("			</table>\r\n");
      out.write("			<a href=\"boardPage.jsp\" class=\"btn btn-primary\">목록</a>\r\n");
      out.write("			");

				if(userID != null && userID.equals(bbs.getUserID())) {
			
      out.write("\r\n");
      out.write("					<a href=\"update.jsp?bbsID=");
      out.print( bbsID);
      out.write("\" class=\"btn btn-primary\">수정</a>\r\n");
      out.write("					<a onclick=\"return confirm('정말로 삭제하시겠습니까?')\" href=\"deleteAction.jsp?bbsID=");
      out.print( bbsID);
      out.write("\" class=\"btn btn-primary\">삭제</a>\r\n");
      out.write("			");
 
				}
			
      out.write("\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("<br><br>\r\n");
      out.write("<!--\r\n");
      out.write("	풋터\r\n");
      out.write("	풋터는 홈페이지의 기타 정보를 보여주는 역할을 하는 일반적으로 홈페이지 가장 아래쪽에 위치한 저작권, 개발자, 내비게이션 등을 포함한다.\r\n");
      out.write("-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<footer style=\"background-color: #000000; color: #ffffff\">\r\n");
      out.write("\r\n");
      out.write("	<div class=\"container\">\r\n");
      out.write("		<br/>\r\n");
      out.write("		<div class=\"row\">\r\n");
      out.write("		\r\n");
      out.write("			<!-- 2 -->\r\n");
      out.write("			<div class=\"col-sm-2\" style=\"text-align: center;\">\r\n");
      out.write("				<h5>Copyright &copy;</h5>\r\n");
      out.write("				<h5>J</h5>\r\n");
      out.write("			</div>\r\n");
      out.write("			\r\n");
      out.write("			<!-- 4 -->\r\n");
      out.write("			<div class=\"col-sm-4\">\r\n");
      out.write("				<h5>대표자 소개</h5>\r\n");
      out.write("				<h5>부트스트랩을 사용해서 웹디자인을 하고 있습니다.</h5>\r\n");
      out.write("			</div>\r\n");
      out.write("			\r\n");
      out.write("			<!-- 2 -->\r\n");
      out.write("			<div class=\"col-sm-2\" style=\"text-align: center;\">\r\n");
      out.write("				<h5>내비게이션</h5>\r\n");
      out.write("				<div class=\"list-group\">\r\n");
      out.write("					<a href=\"#\" class=\"list-group-item\">소개</a>\r\n");
      out.write("					<a href=\"#\" class=\"list-group-item\">강사진</a>\r\n");
      out.write("					<a href=\"#\" class=\"list-group-item\">강의</a>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			\r\n");
      out.write("			<!-- 2 -->\r\n");
      out.write("			<div class=\"col-sm-2\" style=\"text-align: center;\">\r\n");
      out.write("				<h5>SNS</h5>\r\n");
      out.write("				<div class=\"list-group\">\r\n");
      out.write("					<a href=\"#\" class=\"list-group-item\">페이스북</a>\r\n");
      out.write("					<a href=\"#\" class=\"list-group-item\">유튜브</a>\r\n");
      out.write("					<a href=\"#\" class=\"list-group-item\">네이버TV</a>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			\r\n");
      out.write("			<!-- 2 -->\r\n");
      out.write("			<div class=\"col-sm-2\">\r\n");
      out.write("				<h5  style=\"text-align: center;\">\r\n");
      out.write("					<span class=\"glyphicon glyphicon-ok\"></span>&nbsp;by J\r\n");
      out.write("				</h5>\r\n");
      out.write("			</div>\r\n");
      out.write("		\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</footer>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
